<div class="order_history">
<?php if(empty($block->getOrder())){?>
      <h3>No Orders Found...</h3>
<?php }else{?>

<table>
  <tr>
    <th>Customer</th>
    <th>Total Amount</th>
    <th>Quantity</th>
  </tr>
  <?php foreach($block->getOrder() as $order){?>
  <tr>
<?php 
?>
    <td><?php echo $order['customer_firstname'].' '.$order['customer_lastname']?></td>
    <td><?php echo $order['order_currency_code'].' '.$order['grand_total']?></td>
    <td><?php echo round($order['total_qty_ordered'])?></td>
  </tr>
  <?php } ?>
</table>
<?php } ?>
</div>

<?php 

?>