<div class="create_schoolAcc">
<form class="form create account form-create-account" action="<?php echo $block->getBaseurl();?>creation/index/save/" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off" novalidate="novalidate">
    <fieldset class="fieldset create info">
        <legend class="legend"><span>PERSONAL INFORMATION</span></legend><br>
        <div class="field field-name-firstname required">
            <label class="label" for="firstname">
                <span>Organization</span>
            </label>

            <div class="control">
                <input type="text" id="firstname" name="firstname" value="" title="First Name" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
            </div>
        </div>

        <div class="field required">
            <label for="email_address" class="label"><span>Contact name</span></label>
            <div class="control">
                 <input type="text" id="name" name="name" value="" title="First Name" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
            </div>
        </div> 

        <div class="field required">
            <label for="email_address" class="label"><span>Contact Email</span></label>
            <div class="control">
                 <input type="text" id="email" name="email" value="" title="First Name" class="input-text required-entry" data-validate="{required:true, 'validate-email':true}" autocomplete="off" aria-required="true">
            </div>
        </div>   

        
        <div class="field field-name-firstname required">
            <label class="label" for="firstname">
                <span>Phone</span>
            </label>

            <div class="control">
                <input type="text" id="phone" name="phone" value="" title="First Name" class="input-text required-entry" data-validate="{required:true, 'validate-number':true}" autocomplete="off" aria-required="true">
            </div>
        </div>

        <div class="field field-name-firstname required">
            <label class="label" for="firstname">
                <span>Fax</span>
            </label>

            <div class="control">
                <input type="text" id="fax" name="fax" value="" title="First Name" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
            </div>
        </div>


        <div class="field field-name-firstname required">
            <label class="label" for="firstname">
                <span>Address</span>
            </label>

            <div class="control">
                <input type="text" id="address" name="address" value="" title="First Name" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
            </div>
        </div>


        <div class="field field-name-firstname required">
            <label class="label" for="firstname">
                <span>City</span>
            </label>

            <div class="control">
                <input type="text" id="city" name="school_city" value="" title="First Name" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
            </div>
        </div>


        <!-- <div class="field field-name-firstname required">
            <label class="label" for="firstname">
                <span>State</span>
            </label>

            <div class="control">
                <input type="text" id="state" name="state" value="" title="First Name" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
            </div>
        </div> -->


        <div class="field field-name-firstname required">
            <label class="label" for="firstname">
                <span>State</span>
            </label>

            <div class="control">
                <select name="state">
                    <option value="AL">Alabama</option>
                    <option value="AK">Alaska</option>
                    <option value="AZ">Arizona</option>
                    <option value="AR">Arkansas</option>
                    <option value="CA">California</option>
                    <option value="CO">Colorado</option>
                    <option value="CT">Connecticut</option>
                    <option value="DE">Delaware</option>
                    <option value="DC">District Of Columbia</option>
                    <option value="FL">Florida</option>
                    <option value="GA">Georgia</option>
                    <option value="HI">Hawaii</option>
                    <option value="ID">Idaho</option>
                    <option value="IL">Illinois</option>
                    <option value="IN">Indiana</option>
                    <option value="IA">Iowa</option>
                    <option value="KS">Kansas</option>
                    <option value="KY">Kentucky</option>
                    <option value="LA">Louisiana</option>
                    <option value="ME">Maine</option>
                    <option value="MD">Maryland</option>
                    <option value="MA">Massachusetts</option>
                    <option value="MI">Michigan</option>
                    <option value="MN">Minnesota</option>
                    <option value="MS">Mississippi</option>
                    <option value="MO">Missouri</option>
                    <option value="MT">Montana</option>
                    <option value="NE">Nebraska</option>
                    <option value="NV">Nevada</option>
                    <option value="NH">New Hampshire</option>
                    <option value="NJ">New Jersey</option>
                    <option value="NM">New Mexico</option>
                    <option value="NY">New York</option>
                    <option value="NC">North Carolina</option>
                    <option value="ND">North Dakota</option>
                    <option value="OH">Ohio</option>
                    <option value="OK">Oklahoma</option>
                    <option value="OR">Oregon</option>
                    <option value="PA">Pennsylvania</option>
                    <option value="RI">Rhode Island</option>
                    <option value="SC">South Carolina</option>
                    <option value="SD">South Dakota</option>
                    <option value="TN">Tennessee</option>
                    <option value="TX">Texas</option>
                    <option value="UT">Utah</option>
                    <option value="VT">Vermont</option>
                    <option value="VA">Virginia</option>
                    <option value="WA">Washington</option>
                    <option value="WV">West Virginia</option>
                    <option value="WI">Wisconsin</option>
                    <option value="WY">Wyoming</option>
                </select>
            </div>
        </div>

        <div class="field field-name-firstname required">
            <label class="label" for="firstname">
                <span>Zipcode</span>
            </label>

            <div class="control">
                <input type="text" id="zipcode" name="zipcode" value="" title="First Name" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
            </div>
        </div>

    

        <div class="field field-name-firstname required">
            <label class="label" for="firstname">
                <span>Type of Fundraising I am interested in:</span>
            </label>

            <div class="control">
                <select name="typeoffund">
                    <option value="1">Catalog Sales</option>
                    <option value="2">Online Sales</option>
                    <option value="3">Catalog and Online Sales</option>
                </select>
            </div>
        </div>


        <div class="field field-name-firstname required">
            <label class="label" for="firstname">
                <span>Comments</span>
            </label>

            <div class="control">
                <textarea id="comment" name="comment" value="" title="First Name" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true"> </textarea>
            </div>
        </div>





                
    
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="Create an Account"><span>Create an Account</span></button>
        </div>
    </div>
</form>
</div>
<script>
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#form-validate');
    var ignore = null;
    
    dataForm.mage('validation', {
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        }).find('input:text').attr('autocomplete', 'off');

});
</script>

</div>